### ISSUE TITLE
Style guide: document how rules artifacts are mirrored

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#12]
It happens on many releases of many rulesets, where the mirror.bazel.build GCS bucket doesn't contain the artifact.
e.g.
https://github.com/bazelbuild/rules_python/issues/566

@meteorcloudy my understanding is that the bazel-central-registry might provide an automation for mirroring releases, is that true?

**Comment by keith** [comment]
Just a note: at Lyft we have found the mirror.bazel.build mirrors to actually be quite flaky, so we override some dependency URLs just to remove them in place of github whenever possible. I am skeptical we could do much better than github in this case

**Comment by alexeagle** [comment]
Agreed, and rulesets are just one of many from-the-internet dependencies that bazel may fetch. I think any serious user would want a read-through cache like artifactory and configure Bazel downloader to exclusively pull through there, to avoid dependency on liveness of internet hosts.

**Comment by meteorcloudy** [comment]
> @meteorcloudy my understanding is that the bazel-central-registry might provide an automation for mirroring releases, is that true?

Yes, that's right! And we can easily change mirror source at https://github.com/bazelbuild/bazel-central-registry/blob/main/bazel_registry.json#L2. I'm open to suggestion what CDN we should use, the current one is hosted via GCS, so might not be accessible by users in China 😂.

**Comment by alexeagle** [comment]
That's great, thanks @meteorcloudy - I think the SIG only needs to update the rules style guide to reflect what a rules author ought to do.

**Comment by alexeagle** [comment]
I think we can close this as bzlmod will mirror release artifacts to a GCS bucket with no effort required from rules authors.
