### ISSUE TITLE
Add rules to catalog following bazelcon

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#15]
Our catalog so far has only the "canonical" rules (in bazelbuild org or recomended on the Bazel site)

We should expand this. First we need some process for public proposal "add this ruleset" which we should make super-easy. (like PRs to awesome-bazel)

Then we should seed this ourselves with rulesets like
- https://github.com/salesforce/rules_spring
- https://github.com/vmware/rules_oss_audit
- https://github.com/tweag/gazelle_cabal

anything else that came out of Bazelcon?

**Comment by aherrmann** [comment]
https://github.com/tweag/rules_nixpkgs comes to mind. It had also been suggested by others at the proposal stage already.

**Comment by jsharpe** [comment]
I guess one question I had was what does it mean for a rule to be in the catalog? I personally have a list of various github repos which have bazel rules but they are all of varying quality; some I make use of as references for implementing my own versions, others I make use of but they maybe have a narrower scope of appeal.

Are we aiming to build something akin to https://github.com/ossf/scorecard but for bazel rules where we 'score' the maturity of a ruleset?

**Comment by alexeagle** [comment]
Yes, our catalog should help users understand the reliability/maturity of a ruleset and help rules authors understand where more resources are needed to fix up popular-but-undermaintained rules. Ideally also put up some signposts like "if you're looking for Go protoc outputs there are three good choices, here are the tradeoffs between them"

That scorecard repo looks amazing. I didn't really have any idea how we would gather and analyze the information, looks like a place to start.

**Comment by jsharpe** [comment]
https://github.com/hdl/bazel_rules_hdl is another one from bazelcon

**Comment by alexeagle** [comment]
https://github.com/slamdev/rules_helm
