### ISSUE TITLE
list thesayyn/protoc-gen-ts in ruleset table 

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/SIG-rules-authors#30]
Hey,
I was wondering whether `thesayyn/protoc-gen-ts` should be listed in rule table.
https://github.com/thesayyn/protoc-gen-ts#with-bazel is a language-specific generator plugin for typescript with bazel rule.

Note: it has a dependency on rules_nodejs and rules_proto.

**Comment by alexeagle** [comment]
Which rule table is that?

**Comment by thesayyn** [comment]
> Which rule table is that?

the table under section https://bazel-contrib.github.io/SIG-rules-authors/proto-grpc.html#the-ruleset-options

**Comment by alexeagle** [comment]
Ah, sorry I see now. Added!
