### ISSUE TITLE
Flip default for --incompatible_config_setting_private_default_visibility

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#34]
Help to flip the default for https://github.com/bazelbuild/bazel/issues/12933 by explicitly setting `--incompatible_config_setting_private_default_visibility=off` in existing repos under Bazel CI, and land a PR in Bazel to change the default so that new Bazel users get the right value.

**Comment by keith** [comment]
looks like this is happening upstream for 6.x https://github.com/bazelbuild/bazel/issues/12933
