### ISSUE TITLE
Flip default for --incompatible_use_platforms_repo_for_constraints

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#43]
Help finish https://github.com/bazelbuild/bazel/issues/8622 by finding affected projects on Bazel CI and explicitly setting the flag to false, then land a PR in Bazel flipping the default value for new projects.

**Comment by aiuto** [comment]
This has someone in aiuto@'s team assigned to it.

**Comment by alexeagle** [comment]
@aiuto does that mean the SIG should not fund work on this? Should we close our issue?

**Comment by aiuto** [comment]
Exactly. @[aranguyen](https://github.com/aranguyen) is working on it.

**Comment by cgrindel** [comment]
@aranguyen Can you confirm whether this has been implemented?

**Comment by aranguyen** [comment]
@cgrindel yes this has been done but it probably hasn't made it to the most recent release. I submitted the change earlier today. I will update the doc separately. Thanks!

**Comment by alexeagle** [comment]
Was just flipped, caused breakages downstream: https://github.com/bazelbuild/continuous-integration/issues/1404
the team is working on it
