### ISSUE TITLE
Host thundergolfer/bazel-mypy-integration

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#47]
I've been working with @thundergolfer and a client to make Python typechecking work well under Bazel.

Eventually it would be nice for rules_python to provide typechecking, but for now this repo works and might get wider adoption.

It meets the criteria <https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria>:

1. License is MIT
2. Typechecking is a widely needed capability for python users
3. Point of contact is myself
4. Already in use by some companies, and well-documented. Has examples and testing on GH actions
5. Will agree to reply to issues/PRs in 2-3 weeks
6. At least myself and @thundergolfer will review/approve PRs
7. Has been publishing semver releases.
8. Works with Bazel 5

**Comment by thundergolfer** [comment]
Commenting to record my agreement with the above. 👍

**Comment by alexeagle** [comment]
Our hope with this repo is that it becomes more mature and can eventually graduate into rules_python, or perhaps Google will starlarkify the python rules and then it's more trivial to introduce type-checking.

**Comment by alexeagle** [comment]
This was approved in the SIG meeting today.

**Comment by thundergolfer** [comment]
Nice. So I can't make you an admin of `bazel-mypy-integration` because it's a personal repo, and I can't currently transfer the repo because I don't have permissions. I need to get past this error: 

> You don't have permission to create public repositories on bazel-contrib

Which must involve me gaining powers in `bazel-contrib`.

**Comment by alexeagle** [comment]
Try now?

**Comment by thundergolfer** [comment]
Same issue: 

> You don’t have the permission to create public repositories on bazel-contrib
