### ISSUE TITLE
BCR Launch: Implement two GitHub apps to publish to BCR

### ISSUE THREAD

**Issue by cgrindel** [bazel-contrib/SIG-rules-authors#55]
Original Single App Work:  https://github.com/publish-to-bcr-dev-registry/bazel-central-registry

Xudong requests that we write two apps to avoid BCR granting the write permission for PR creation.

**Comment by cgrindel** [comment]
Existing [Publish to BCR repository](https://github.com/bazel-contrib/publish-to-bcr).

**Comment by alexeagle** [comment]
I think this is done now, it's in use by several rulesets and nicely documented.
