### ISSUE TITLE
Write a tutorial for Bazel + Go

### ISSUE THREAD

**Issue by cgrindel** [bazel-contrib/SIG-rules-authors#60]
Look like the C++ and Java tutorials.

Repo: ???

**Comment by cgrindel** [comment]
Assigned: Chris Love

**Comment by cgrindel** [comment]
Replaced by https://github.com/bazel-contrib/Bazel-learning-paths/issues/5.

**Comment by cgrindel** [comment]
@chrislovecnm comment from other issue:
> @alexeagle was saying to place the tutorial under https://github.com/bazel-contrib/SIG-rules-authors/tree/gh-pages for the time being. I can then work with Radhika and the bazel team to see if it makes sense to move it under the bazel website. That or we need a link from the bazel website to the bazel contrib gh pages site.

**Comment by chrislovecnm** [comment]
We are waiting on the source code to get merged

**Comment by chrislovecnm** [comment]
Once https://github.com/bazelbuild/rules_go/pull/3317 and https://github.com/bazel-contrib/SIG-rules-authors/pull/67 are merged, we can close this
