### ISSUE TITLE
Use Renovate to keep repositories update to date

### ISSUE THREAD

**Issue by chrislovecnm** [bazel-contrib/SIG-rules-authors#65]
Hi all

When I was working with Google on PSO projects, we used Renovate to keep rule versions up to date.  Here is the support https://docs.renovatebot.com/bazel/

Does anyone have an issue with starting to use it?

**Comment by cgrindel** [comment]
If we add it, we should add it to [the Bazel Learning Paths repo](https://github.com/bazel-contrib/Bazel-learning-paths). Does that seem right?

**Comment by jsharpe** [comment]
No issue; I use it extensively internally.
One thing to note is it doesn't work if the WORKSPACE file is using variables to set things like sha's as it's just a glorified text replacement engine and not a starlark interpretor. 
The other question is do we self-host an instance on github actions or do we use the public one? Given all the repos are public anyway I'd say we're fine with the public instance?

**Comment by alexeagle** [comment]
I'm not sure which "repositories" you're referencing here. Do you mean this repo itself? Other repositories in the bazel-contrib org? I've enabled the Renovate app for all repos in the org now so I think this can be closed.
