### ISSUE TITLE
Create bazel-contrib/bazel_features

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/SIG-rules-authors#80]
Following the [Bazel feature detection in Starlark](https://docs.google.com/document/d/1HJf3gMYIrzmTRqbD4nWXH2eJRHXjLrOU0mmIeZplUzY/edit#) proposal, we would like to start the new `bazel_features` repository to provide helpers that perform feature detection for Bazel.

> Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

SG

> Must have wide applicability in the community.

This repository is expected to be useful for rule sets which need to keep compatibility with different Bazel versions.

> Must have a clear point of contact who answers questions from the SIG.

From Bazel team: @meteorcloudy @Wyverald @comius
From community: maybe @fmeum, more community owners are welcome.

> Must be “production quality”: clear README or other documentation outlining the goal of these rules, how to use them etc.

There are already some details in the design doc, we'll compose a README file based on that.

> generated API documentation include examples of use

Basic instructions and examples will be available. Documentation for each function can probably be generated with Stardoc, but those functions should be very simple and self-explanatory anyway.

> tests that are running continuously

Minimal unit and integration tests should be implemented.

> Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)
> Must have more than one person who is committed to review/approve PRs
> We recommend encoding this as a CODEOWNERS file.

Initially this will be maintained by the Bazel team (@meteorcloudy @Wyverald @comius), but volunteering community maintainers are very welcome and appreaciated!

> Must publish semver releases.

This project itself should always be backwards compatible, so following semver is no problem.

> Optional: follow the same release pattern as the rules-template does.

Not an actual build rule, so not applicable.

> Must work with LTS Bazel version

Probably going to be the most Bazel compatible project ever.

**Comment by fmeum** [comment]
I'm in!

**Comment by alexeagle** [comment]
Okay, https://github.com/bazel-contrib/bazel_features/ is created!
