### ISSUE TITLE
Host musl-toolchain

### ISSUE THREAD

**Issue by illicitonion** [bazel-contrib/SIG-rules-authors#84]
As discussed in previous meetings, we have scripted the creation of a `cc_toolchain` which uses [`musl`](https://musl.libc.org) to produce statically-linked binaries, and which can be built cross-platform (e.g. Linux binaries can be built from macOS).

From [the criteria](https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria):
1. Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

Happy to Apache-2.0.

2. Must have wide applicability in the community.

Yes - this applies to anyone who wants a C++ toolchain with Bazel, similar to https://github.com/aspect-build/gcc-toolchain. 

3. Must have a clear point of contact who answers questions from the SIG.

Yes - @illicitonion

4. Must be “production quality”:

Yes - my company has been using this and releasing binaries to production based on it for several years. There's no reason this wouldn't reasonably apply to any other user too.

5. Clear README or other documentation outlining the goal of these rules, how to use them etc.
* generated API documentation
* include examples of use
* tests that are running continuously

Yes - We have CI that verifies binaries built on each of {linux x86-64, macOS x86-64, macOS arm64} successfully run on a linux x86-64 worker, and a README explaining how to use. We don't have API documentation similar to https://github.com/aspect-build/gcc-toolchain the API is just: register the toolchain.

6. Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)

Yes.

6. Must have more than one person who is committed to review/approve PRs

@illicitonion and @gibfahn have signed up as initial maintainers, my company can provide more if needed.

7. Must publish semver releases.

Sure.

8. Must work with LTS Bazel version

CI currently tests 6.3.2. Happy to target future LTSes as they're released.

**Comment by illicitonion** [comment]
Initial code-drop: https://github.com/bazel-contrib/musl-toolchain/pull/1

**Comment by illicitonion** [comment]
Screenshot of what the generated GitHub actions end up like:

<img width="1359" alt="Screenshot 2023-10-24 at 13 37 13" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/1131704/bee603c3-f9e7-4b75-b927-84f65b0146a3">

Screenshot of what a generated release looks like:

<img width="1232" alt="Screenshot 2023-10-24 at 13 37 38" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/1131704/64c035f5-306c-49a6-aaba-dc9758426a4f">

Something worth calling out: The ARM macOS build requires billing to be enabled for the org, and the "build musl" actions are _sloooow_, so the other platforms will reasonably quickly churn through the free actions quota.

**Comment by cgrindel** [comment]
Approved at the Bazel Rules SIG meeting on 2023-10-31 without the arm MacOS CI runners.

**Comment by cgrindel** [comment]
@illicitonion When the CI MacOS arm stuff is disabled, let us know and we can get someone to approve the PR.

**Comment by illicitonion** [comment]
I just pushed https://github.com/bazel-contrib/musl-toolchain/pull/1/commits/af7cfa292cb4392861f3a60218d30ebfbd26dfd4 removing the macOS ARM support :) Thanks @cgrindel!

**Comment by alexeagle** [comment]
Is there more to do on this issue, or can it be closed?
