### ISSUE TITLE
Host rules_ruby

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#87]
Following a meeting with maintainers of existing ruby_rules, we decided that bazel-contrib is the right place to promote https://github.com/p0deje/rules_ruby to be the "canonical" Ruby ruleset for Bazel, and publish as `rules_ruby` on the Bazel Central Registry.

Following the criteria from the [Adding a repo process](https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria)

> Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

The [existing Apache 2](https://github.com/p0deje/rules_ruby/blob/main/LICENSE) license will be retained.

> Must have wide applicability in the community.

https://www.tiobe.com/tiobe-index/ has Ruby in the top 20 (above Rust!)

> Must have a clear point of contact who answers questions from the SIG.

I'll be the SIG point-of-contact for rules_ruby

> Must be “production quality”:
> clear README or other documentation outlining the goal of these rules, how to use them etc.
> generated API documentation
> include examples of use
> tests that are running continuously

These things are already largely in-place, and we will do some more cleanup as part of moving it.

> Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)

@p0deje and @kigster are you okay with committing to this level of responsiveness?

> Must have more than one person who is committed to review/approve PRs

Myself, @p0deje and @kigster will be initial maintainers

> Must publish semver releases.

I'll add release automation like the rules-template, and we'll follow semver principles for numbering releases.

> Must work with LTS Bazel version

Currently supports Bazel 6, we will add testing for Bazel 7

> Must publish the rules to the [Bazel Central Registry](https://github.com/bazelbuild/bazel-central-registry), keep that CI green

I'll add bzlmod support.

**Comment by p0deje** [comment]
> Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)

Fine by me.

**Comment by cgrindel** [comment]
The attendees at today's (2023-11-28) Bazel Rules Author SIG meeting approved the hosting of `rules_ruby` in `bazel-contrib`.

**Comment by alexeagle** [comment]
This was done a while ago: https://github.com/bazel-contrib/rules_ruby
