### ISSUE TITLE
Host rules_debian_packages

### ISSUE THREAD

**Issue by betaboon** [bazel-contrib/SIG-rules-authors#88]
After some discussions with @alexeagle, I'd like to donate https://github.com/betaboon/rules_debian_packages.

Following the criteria from the [Adding a repo process](https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria)

> Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

The project is already released under [apache 2](https://github.com/betaboon/rules_debian_packages/blob/main/LICENSE) license 

> Must have wide applicability in the community.

I've been using the project to build custom images for quite a while.
This project could provide [support for installing apt packages](https://github.com/bazel-contrib/rules_oci/issues/375) for `rules_oci`.

> Must have a clear point of contact who answers questions from the SIG.

TBD

> Must be “production quality”:
>     clear README or other documentation outlining the goal of these rules, how to use them etc.
>     generated API documentation
>     include examples of use
>     tests that are running continuously

Most of this is already in-place.

> Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)

I'm fine with this SLA. 

> Must have more than one person who is committed to review/approve PRs

Any volunteers?

> Must publish semver releases.

This is already in place, as the project has recently been rebased on [rules-template](https://github.com/bazel-contrib/rules-template)

> Must work with LTS Bazel version

Smoke-tests currently cover 5.4.0 and 6.4.0.
Tests for 7.0.0 are currently missing.

> Must publish the rules to the [Bazel Central Registry](https://github.com/bazelbuild/bazel-central-registry), keep that CI green

bzlmod support is currently missing.
I'd be happy to get some help on that.

**Comment by alexeagle** [comment]
Let's have @thesayyn as the secondary reviewer/maintainer

**Comment by alexeagle** [comment]
FYI @nacl - does this overlap with work you've done in rules_pkg?

**Comment by cgrindel** [comment]
The application for inclusion of `rules_debian_packages` was discussed at today's Bazel Rules Author SIG meeting. The attendees consented to the inclusion of this repository under `bazel-contrib`.

**Comment by betaboon** [comment]
what are the further steps to be taken now?

**Comment by cgrindel** [comment]
@betaboon You need to initiate [the repo transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) in GitHub. However, you will need permission to create a repo in `bazel-contrib`.

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

@alexeagle I do not have permission to set up @betaboon. Is that something that you can do?

**Comment by alexeagle** [comment]
Yes I'll work on this

**Comment by alexeagle** [comment]
This is done now, https://github.com/bazel-contrib/rules_debian_packages/
