### ISSUE TITLE
Looks like rules-proto-grpc/rules_proto_grpc no longer supports java

### ISSUE THREAD

**Issue by wcurrie** [bazel-contrib/SIG-rules-authors#90]
As of this commit https://github.com/rules-proto-grpc/rules_proto_grpc/commit/8b8dc50f090f1804c351a636134b3e480966c3f9, it looks like there's no support for java in rules-proto-grpc. Should the table [here](https://bazel-contrib.github.io/SIG-rules-authors/proto-grpc.html) be updated?

<img width="780" alt="image" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/2050920/19191e05-9dab-4aa1-b6de-801e9905145c">

There's no java listed [here](https://rules-proto-grpc.com/en/latest/#supported-languages-and-tools) either

<img width="643" alt="image" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/2050920/05d25242-6df3-44e7-9cde-7034b0ff9153">

Maybe the [rule](https://github.com/grpc/grpc-java/blob/9ab35b05de0709c0547e38bb0f2d3805dd5618e2/java_grpc_library.bzl#L179) from grpc-java should be mentioned instead?

From the discussion [here](https://github.com/bazelbuild/bazel-central-registry/issues/353#issuecomment-1379293719), maybe the desired state isn't known yet: 

> Do you have a recommendation of which one?

**Comment by cgrindel** [comment]
Based upon [this issue](https://github.com/rules-proto-grpc/rules_proto_grpc/issues/299), it looks like they intend to support it. Since this seems related to the migration to bzlmod and java support is available on their legacy branch, I recommend that we not update the table.

**Comment by wcurrie** [comment]
Ah, so maybe the plan/thinking is java support back to the master branch after they work out how to add bzlmod support to grpc-java. That's probably what is explained in https://github.com/rules-proto-grpc/rules_proto_grpc/issues/269

>  Step 1 on this process will be a minimum viable module that maybe just supports a single language.

I'd not understood that sorry. It's currently a bit confusing since the generated rules-proto-grpc docs linked from the [legacy](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/legacy) branch (and served from googling) don't mention java right now

> Full documentation for the current and previous versions [can be found here](https://rules-proto-grpc.com/)

Thanks!

**Comment by wcurrie** [comment]
Noting for anybody else. On the docs site, there's a version toggle at the bottom. Switch off latest to see the docs about java

<img width="300" alt="image" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/2050920/456e1808-299c-41f6-87a2-5a87a3a57a1a">

https://rules-proto-grpc.com/en/4.5.0/

And there's a note in the readme too

<img width="833" alt="image" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/2050920/5f854513-7eea-4041-9071-6a593f46b091">
