### ISSUE TITLE
Host toolchains_llvm

### ISSUE THREAD

**Issue by siddharthab** [bazel-contrib/SIG-rules-authors#92]
Asking to move github.com/grailbio/bazel-toolchain to github.com/bazel-contrib/toolchains_llvm.

[Criteria](https://bazelbuild.slack.com/archives/CDCMRLS23/p1707157866988289) check:
1. Uses Apache 2.0 license
2. Used widely in the community.
3. I can be the point of contact for the SIG.
4. Code is production quality, and is used by many orgs:
    - clear README is included.
    - API documentation; currently only in-code and not generated separately, but in a state where generation should be easy.
    - examples of use are provided through tests and within documentation.
    - Continuously tested for every PR and periodically.
5. Issues and PRs are addressed by members in the community. I can take an active role in triaging these, going forward.
6. Multiple people participate in PR reviews and merges
    - Can formalize this as a CODEOWNERS file after the move.
7. Release versions are semver.
8. Can support all Bazel LTS going forward, but community prefers to drop support for non-current versions to keep things simple.
9. Rules are already published to BCR and CI is green.

Some original discussion in https://bazelbuild.slack.com/archives/CDCMRLS23/p1707157866988289.

**Comment by alexeagle** [comment]
Could you nominate who should be the other folks that end up in the `CODEOWNERS` file? I think we want their consent to this before approving.
Maybe @jsharpe or @fmeum is interested?

**Comment by siddharthab** [comment]
Yes, either or both of these would work. Also, @rrbutani, would you be open as well?

**Comment by rrbutani** [comment]
Absolutely!

**Comment by fmeum** [comment]
If you need more codeowners, feel free to add me as well.

**Comment by sluongng** [comment]
This is amazing @siddharthab. Grail's llvm toolchain has always been the reference implementation for me.

Thanks a ton for doing this. 🙏

**Comment by jsharpe** [comment]
Yes, I'm happy to be listed on CODEOWNERS if needed.

**Comment by cgrindel** [comment]
Discussed at Bazel Rules Author SIG meeting and approved by those present.

**Comment by siddharthab** [comment]
Thank you. I have asked the org admins at github.com/grailbio for a final check. It might take some time.

**Comment by siddharthab** [comment]
The transfer is now done. I will set up some branch protection rules, etc. to enforce code reviews and other best practices. Please feel free to close this issue, or let me know if you see something missing.
