### ISSUE TITLE
Host setup-bazel

### ISSUE THREAD

**Issue by p0deje** [bazel-contrib/SIG-rules-authors#93]
Following the discussion in https://groups.google.com/g/bazel-contrib/c/i30IN01PHOM, the suggestion is to host https://github.com/p0deje/setup-bazel under bazel-contrib organization to make it a default GitHub Action for setting up Bazelisk and Bazel. The https://github.com/bazelbuild/setup-bazelisk/ would then be archived in favor of the bazel-contrib one.

Following the criteria from the [Adding a repo process](https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria)

> Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

It's MIT currently.

> Must have wide applicability in the community.

Not quite, it's only actively used in a Selenium project https://github.com/search?q=p0deje%2Fsetup-bazel+repo%3ASeleniumHQ%2Fselenium&type=code.

> Must have a clear point of contact who answers questions from the SIG.

@alexeagle or @p0deje can be a point of contact.

> Must be “production quality”:
clear README or other documentation outlining the goal of these rules, how to use them etc.
generated API documentation
include examples of use
tests that are running continuously

Mostly in-place, but some improvements are still to be done (especially CI and tests).

> Must reply to issues/PRs in 2-3 weeks (exact service level agreement TBD)

I'm fine with that.

> Must have more than one person who is committed to review/approve PRs

I am not sure who could be the second person.

> Must publish semver releases.

Is already done, though there is no specific automation.

> Must work with LTS Bazel version

Currently works both with Bazel 6 and 7.

> Must publish the rules to the [Bazel Central Registry](https://github.com/bazelbuild/bazel-central-registry), keep that CI green

This is not related to the GitHub Actions.

**Comment by junyer** [comment]
Many thanks for getting the ball rolling, @p0deje!

> Not quite, it's only actively used in a Selenium project https://github.com/search?q=p0deje%2Fsetup-bazel+repo%3ASeleniumHQ%2Fselenium&type=code.

... and now by RE2 as per https://github.com/search?q=p0deje%2Fsetup-bazel+repo%3Agoogle%2Fre2&type=code. :)

> I am not sure who could be the second person.

If there's absolutely nobody better, I volunteer as tribute.

**Comment by alexeagle** [comment]
Added to agenda for the next SIG meeting

**Comment by alexeagle** [comment]
> If there's absolutely nobody better, I volunteer as tribute.

Thanks for offering @junyer - we don't have any other suggestions for a secondary reviewer so I think that's you.

The SIG met today and there's no objection, so this is approved. @p0deje I think you already have the needed access to transfer the repo to bazel-contrib - if not please let me know!

Thanks to both of you 🙏🏻

**Comment by alexeagle** [comment]
sorry, closed too soon. We should keep it open for the migration process.

**Comment by p0deje** [comment]
Repository transferred, I would like to publish an action to GitHub Marketplace, but I can't yet:
<img width="955" alt="Screenshot 2024-03-09 at 11 04 35" src="https://github.com/bazel-contrib/SIG-rules-authors/assets/665846/98cc7cbb-8777-40be-9a4f-2a38ab9f730f">

@alexeagle Can you help with that?

**Comment by junyer** [comment]
Thanks, @p0deje!

FYI, @meteorcloudy and @mishas, I pushed https://github.com/bazelbuild/setup-bazelisk/commit/fd3aad34401d7d14c066d58ef572f94ae134a8cd and archived the repository.

**Comment by junyer** [comment]
BTW, GitHub Marketplace is desirable, but not necessary: I'm happy to report that using `bazel-contrib/setup-bazel@0.8.0` works fine for RE2 already. :)

**Comment by alexeagle** [comment]
I accepted the Marketplace terms of service on behalf of bazel-contrib. It now says the name you wanted is already taken, so I think you're on to the next step

**Comment by alexeagle** [comment]
I think this ticket is complete since the repo is moved.

**Comment by junyer** [comment]
Thanks, @alexeagle!
