### ISSUE TITLE
Host bazelrc-parser-go

### ISSUE THREAD

**Issue by illicitonion** [bazel-contrib/SIG-rules-authors#97]
In [a drive-by comment on a PR](https://github.com/bazelbuild/bazel/pull/19536#issuecomment-1793662427) @sluongng mentioned an interest in having a shared bazelrc parsing logic written in Go. I have extracted one from internal code to hand over to bazel-contrib if folks are interested :)

1. Must use an open-source license, preferably [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

Apache 2 is fine.

2. Must have wide applicability in the community.

We've written one, it sounds like buildbuddy have one, I know bits of the aspect CLI also implement some code around cleanly calling `bazel help flags-as-proto` to get related metadata. I think this is reasonably common code to want in wrappers around Bazel, and those seem to mostly be written in Go.

3. Must have a clear point of contact who answers questions from the SIG.

@illicitonion 

4. Must be “production quality”:

It's a repo with unit tests and a README, which has been in use for 1+ year at Apple.

6. Must reply to issues/PRs in 2-3 weeks

Happy to sign up to this, related to the next question:

7. Must have more than one person who is committed to review/approve PRs

@gibfahn and @stevebarrau are happy to volunteer, hopefully @sluongng would be interested too, open to more volunteers!

8. Must publish semver releases.

Will follow the Go conventions (i.e. avoid breaking changes, new major versions for major changes).

9. Must work with LTS Bazel version

Not a ruleset, but expect to support whatever new constructs come up.

10. Must publish the rules to the [Bazel Central Registry](https://github.com/bazelbuild/bazel-central-registry), keep that CI green

Not a ruleset.

**Comment by cgrindel** [comment]
The Rules Author SIG approved to bring into bazel-contrib on 2024-04-30.

**Comment by illicitonion** [comment]
https://github.com/bazel-contrib/bazelrc-parser-go now has content 🎉 thanks all!

**Comment by sluongng** [comment]
> hopefully @sluongng would be interested too

We do maintain our own currently with some elaborate logic to support our own CLI's plugin system. If there are benefits in adopting this newer parser, we would love to contribute back.

Thanks so much for reaching out ❤️ 🍎
